from typing import Any

class PyRay:
    def pointer(self, struct):
        return ffi.addressof(struct)

    BLEND_ADDITIVE: int
    BLEND_ADD_COLORS: int
    BLEND_ALPHA: int
    BLEND_CUSTOM: int
    BLEND_MULTIPLIED: int
    BLEND_SUBTRACT_COLORS: int
    def begin_blend_mode(self, int_0: int) -> None: ...
    def begin_drawing(self) -> None: ...
    def begin_mode_2d(self, Camera2D_0: Any) -> None: ...
    def begin_mode_3d(self, Camera3D_0: Any) -> None: ...
    def begin_scissor_mode(self, int_0: int, int_1: int, int_2: int, int_3: int) -> None: ...
    def begin_shader_mode(self, Shader_0: Any) -> None: ...
    def begin_texture_mode(self, RenderTexture_0: Any) -> None: ...
    def begin_vr_stereo_mode(self, VrStereoConfig_0: Any) -> None: ...
    CAMERA_CUSTOM: int
    CAMERA_FIRST_PERSON: int
    CAMERA_FREE: int
    CAMERA_ORBITAL: int
    CAMERA_ORTHOGRAPHIC: int
    CAMERA_PERSPECTIVE: int
    CAMERA_THIRD_PERSON: int
    CUBEMAP_LAYOUT_AUTO_DETECT: int
    CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE: int
    CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR: int
    CUBEMAP_LAYOUT_LINE_HORIZONTAL: int
    CUBEMAP_LAYOUT_LINE_VERTICAL: int
    CUBEMAP_LAYOUT_PANORAMA: int
    def change_directory(self, str_0: str) -> bool: ...
    def check_collision_box_sphere(self, BoundingBox_0: Any, Vector3_1: Any, float_2: float) -> bool: ...
    def check_collision_boxes(self, BoundingBox_0: Any, BoundingBox_1: Any) -> bool: ...
    def check_collision_circle_rec(self, Vector2_0: Any, float_1: float, Rectangle_2: Any) -> bool: ...
    def check_collision_circles(self, Vector2_0: Any, float_1: float, Vector2_2: Any, float_3: float) -> bool: ...
    def check_collision_lines(self, Vector2_0: Any, Vector2_1: Any, Vector2_2: Any, Vector2_3: Any, Vector2_pointer_4: Any) -> bool: ...
    def check_collision_point_circle(self, Vector2_0: Any, Vector2_1: Any, float_2: float) -> bool: ...
    def check_collision_point_rec(self, Vector2_0: Any, Rectangle_1: Any) -> bool: ...
    def check_collision_point_triangle(self, Vector2_0: Any, Vector2_1: Any, Vector2_2: Any, Vector2_3: Any) -> bool: ...
    def check_collision_ray_box(self, Ray_0: Any, BoundingBox_1: Any) -> bool: ...
    def check_collision_ray_sphere(self, Ray_0: Any, Vector3_1: Any, float_2: float) -> bool: ...
    def check_collision_ray_sphere_ex(self, Ray_0: Any, Vector3_1: Any, float_2: float, Vector3_pointer_3: Any) -> bool: ...
    def check_collision_recs(self, Rectangle_0: Any, Rectangle_1: Any) -> bool: ...
    def check_collision_spheres(self, Vector3_0: Any, float_1: float, Vector3_2: Any, float_3: float) -> bool: ...
    def clear_background(self, Color_0: Any) -> None: ...
    def clear_directory_files(self) -> None: ...
    def clear_dropped_files(self) -> None: ...
    def clear_window_state(self, unsignedint_0: int) -> None: ...
    def close_audio_device(self) -> None: ...
    def close_audio_stream(self, AudioStream_0: Any) -> None: ...
    def close_window(self) -> None: ...
    def codepoint_to_utf8(self, int_0: int, int_pointer_1: Any) -> str: ...
    def color_alpha(self, Color_0: Any, float_1: float) -> Any: ...
    def color_alpha_blend(self, Color_0: Any, Color_1: Any, Color_2: Any) -> Any: ...
    def color_from_hsv(self, float_0: float, float_1: float, float_2: float) -> Any: ...
    def color_from_normalized(self, Vector4_0: Any) -> Any: ...
    def color_normalize(self, Color_0: Any) -> Any: ...
    def color_to_hsv(self, Color_0: Any) -> Any: ...
    def color_to_int(self, Color_0: Any) -> int: ...
    def compress_data(self, unsignedstr_0: str, int_1: int, int_pointer_2: Any) -> str: ...
    def decompress_data(self, unsignedstr_0: str, int_1: int, int_pointer_2: Any) -> str: ...
    def directory_exists(self, str_0: str) -> bool: ...
    def disable_cursor(self) -> None: ...
    def draw_billboard(self, Camera3D_0: Any, Texture_1: Any, Vector3_2: Any, float_3: float, Color_4: Any) -> None: ...
    def draw_billboard_rec(self, Camera3D_0: Any, Texture_1: Any, Rectangle_2: Any, Vector3_3: Any, float_4: float, Color_5: Any) -> None: ...
    def draw_bounding_box(self, BoundingBox_0: Any, Color_1: Any) -> None: ...
    def draw_circle(self, int_0: int, int_1: int, float_2: float, Color_3: Any) -> None: ...
    def draw_circle_3d(self, Vector3_0: Any, float_1: float, Vector3_2: Any, float_3: float, Color_4: Any) -> None: ...
    def draw_circle_gradient(self, int_0: int, int_1: int, float_2: float, Color_3: Any, Color_4: Any) -> None: ...
    def draw_circle_lines(self, int_0: int, int_1: int, float_2: float, Color_3: Any) -> None: ...
    def draw_circle_sector(self, Vector2_0: Any, float_1: float, float_2: float, float_3: float, int_4: int, Color_5: Any) -> None: ...
    def draw_circle_sector_lines(self, Vector2_0: Any, float_1: float, float_2: float, float_3: float, int_4: int, Color_5: Any) -> None: ...
    def draw_circle_v(self, Vector2_0: Any, float_1: float, Color_2: Any) -> None: ...
    def draw_cube(self, Vector3_0: Any, float_1: float, float_2: float, float_3: float, Color_4: Any) -> None: ...
    def draw_cube_texture(self, Texture_0: Any, Vector3_1: Any, float_2: float, float_3: float, float_4: float, Color_5: Any) -> None: ...
    def draw_cube_v(self, Vector3_0: Any, Vector3_1: Any, Color_2: Any) -> None: ...
    def draw_cube_wires(self, Vector3_0: Any, float_1: float, float_2: float, float_3: float, Color_4: Any) -> None: ...
    def draw_cube_wires_v(self, Vector3_0: Any, Vector3_1: Any, Color_2: Any) -> None: ...
    def draw_cylinder(self, Vector3_0: Any, float_1: float, float_2: float, float_3: float, int_4: int, Color_5: Any) -> None: ...
    def draw_cylinder_wires(self, Vector3_0: Any, float_1: float, float_2: float, float_3: float, int_4: int, Color_5: Any) -> None: ...
    def draw_ellipse(self, int_0: int, int_1: int, float_2: float, float_3: float, Color_4: Any) -> None: ...
    def draw_ellipse_lines(self, int_0: int, int_1: int, float_2: float, float_3: float, Color_4: Any) -> None: ...
    def draw_fps(self, int_0: int, int_1: int) -> None: ...
    def draw_grid(self, int_0: int, float_1: float) -> None: ...
    def draw_line(self, int_0: int, int_1: int, int_2: int, int_3: int, Color_4: Any) -> None: ...
    def draw_line_3d(self, Vector3_0: Any, Vector3_1: Any, Color_2: Any) -> None: ...
    def draw_line_bezier(self, Vector2_0: Any, Vector2_1: Any, float_2: float, Color_3: Any) -> None: ...
    def draw_line_bezier_quad(self, Vector2_0: Any, Vector2_1: Any, Vector2_2: Any, float_3: float, Color_4: Any) -> None: ...
    def draw_line_ex(self, Vector2_0: Any, Vector2_1: Any, float_2: float, Color_3: Any) -> None: ...
    def draw_line_strip(self, Vector2_pointer_0: Any, int_1: int, Color_2: Any) -> None: ...
    def draw_line_v(self, Vector2_0: Any, Vector2_1: Any, Color_2: Any) -> None: ...
    def draw_mesh(self, Mesh_0: Any, Material_1: Any, Matrix_2: Any) -> None: ...
    def draw_mesh_instanced(self, Mesh_0: Any, Material_1: Any, Matrix_pointer_2: Any, int_3: int) -> None: ...
    def draw_model(self, Model_0: Any, Vector3_1: Any, float_2: float, Color_3: Any) -> None: ...
    def draw_model_ex(self, Model_0: Any, Vector3_1: Any, Vector3_2: Any, float_3: float, Vector3_4: Any, Color_5: Any) -> None: ...
    def draw_model_wires(self, Model_0: Any, Vector3_1: Any, float_2: float, Color_3: Any) -> None: ...
    def draw_model_wires_ex(self, Model_0: Any, Vector3_1: Any, Vector3_2: Any, float_3: float, Vector3_4: Any, Color_5: Any) -> None: ...
    def draw_pixel(self, int_0: int, int_1: int, Color_2: Any) -> None: ...
    def draw_pixel_v(self, Vector2_0: Any, Color_1: Any) -> None: ...
    def draw_plane(self, Vector3_0: Any, Vector2_1: Any, Color_2: Any) -> None: ...
    def draw_point_3d(self, Vector3_0: Any, Color_1: Any) -> None: ...
    def draw_poly(self, Vector2_0: Any, int_1: int, float_2: float, float_3: float, Color_4: Any) -> None: ...
    def draw_poly_lines(self, Vector2_0: Any, int_1: int, float_2: float, float_3: float, Color_4: Any) -> None: ...
    def draw_ray(self, Ray_0: Any, Color_1: Any) -> None: ...
    def draw_rectangle(self, int_0: int, int_1: int, int_2: int, int_3: int, Color_4: Any) -> None: ...
    def draw_rectangle_gradient_ex(self, Rectangle_0: Any, Color_1: Any, Color_2: Any, Color_3: Any, Color_4: Any) -> None: ...
    def draw_rectangle_gradient_h(self, int_0: int, int_1: int, int_2: int, int_3: int, Color_4: Any, Color_5: Any) -> None: ...
    def draw_rectangle_gradient_v(self, int_0: int, int_1: int, int_2: int, int_3: int, Color_4: Any, Color_5: Any) -> None: ...
    def draw_rectangle_lines(self, int_0: int, int_1: int, int_2: int, int_3: int, Color_4: Any) -> None: ...
    def draw_rectangle_lines_ex(self, Rectangle_0: Any, int_1: int, Color_2: Any) -> None: ...
    def draw_rectangle_pro(self, Rectangle_0: Any, Vector2_1: Any, float_2: float, Color_3: Any) -> None: ...
    def draw_rectangle_rec(self, Rectangle_0: Any, Color_1: Any) -> None: ...
    def draw_rectangle_rounded(self, Rectangle_0: Any, float_1: float, int_2: int, Color_3: Any) -> None: ...
    def draw_rectangle_rounded_lines(self, Rectangle_0: Any, float_1: float, int_2: int, int_3: int, Color_4: Any) -> None: ...
    def draw_rectangle_v(self, Vector2_0: Any, Vector2_1: Any, Color_2: Any) -> None: ...
    def draw_ring(self, Vector2_0: Any, float_1: float, float_2: float, float_3: float, float_4: float, int_5: int, Color_6: Any) -> None: ...
    def draw_ring_lines(self, Vector2_0: Any, float_1: float, float_2: float, float_3: float, float_4: float, int_5: int, Color_6: Any) -> None: ...
    def draw_sphere(self, Vector3_0: Any, float_1: float, Color_2: Any) -> None: ...
    def draw_sphere_ex(self, Vector3_0: Any, float_1: float, int_2: int, int_3: int, Color_4: Any) -> None: ...
    def draw_sphere_wires(self, Vector3_0: Any, float_1: float, int_2: int, int_3: int, Color_4: Any) -> None: ...
    def draw_text(self, str_0: str, int_1: int, int_2: int, int_3: int, Color_4: Any) -> None: ...
    def draw_text_codepoint(self, Font_0: Any, int_1: int, Vector2_2: Any, float_3: float, Color_4: Any) -> None: ...
    def draw_text_ex(self, Font_0: Any, str_1: str, Vector2_2: Any, float_3: float, float_4: float, Color_5: Any) -> None: ...
    def draw_text_rec(self, Font_0: Any, str_1: str, Rectangle_2: Any, float_3: float, float_4: float, _Bool_5: bool, Color_6: Any) -> None: ...
    def draw_text_rec_ex(self, Font_0: Any, str_1: str, Rectangle_2: Any, float_3: float, float_4: float, _Bool_5: bool, Color_6: Any, int_7: int, int_8: int, Color_9: Any, Color_10: Any) -> None: ...
    def draw_texture(self, Texture_0: Any, int_1: int, int_2: int, Color_3: Any) -> None: ...
    def draw_texture_ex(self, Texture_0: Any, Vector2_1: Any, float_2: float, float_3: float, Color_4: Any) -> None: ...
    def draw_texture_n_patch(self, Texture_0: Any, NPatchInfo_1: Any, Rectangle_2: Any, Vector2_3: Any, float_4: float, Color_5: Any) -> None: ...
    def draw_texture_poly(self, Texture_0: Any, Vector2_1: Any, Vector2_pointer_2: Any, Vector2_pointer_3: Any, int_4: int, Color_5: Any) -> None: ...
    def draw_texture_pro(self, Texture_0: Any, Rectangle_1: Any, Rectangle_2: Any, Vector2_3: Any, float_4: float, Color_5: Any) -> None: ...
    def draw_texture_quad(self, Texture_0: Any, Vector2_1: Any, Vector2_2: Any, Rectangle_3: Any, Color_4: Any) -> None: ...
    def draw_texture_rec(self, Texture_0: Any, Rectangle_1: Any, Vector2_2: Any, Color_3: Any) -> None: ...
    def draw_texture_tiled(self, Texture_0: Any, Rectangle_1: Any, Rectangle_2: Any, Vector2_3: Any, float_4: float, float_5: float, Color_6: Any) -> None: ...
    def draw_texture_v(self, Texture_0: Any, Vector2_1: Any, Color_2: Any) -> None: ...
    def draw_triangle(self, Vector2_0: Any, Vector2_1: Any, Vector2_2: Any, Color_3: Any) -> None: ...
    def draw_triangle_3d(self, Vector3_0: Any, Vector3_1: Any, Vector3_2: Any, Color_3: Any) -> None: ...
    def draw_triangle_fan(self, Vector2_pointer_0: Any, int_1: int, Color_2: Any) -> None: ...
    def draw_triangle_lines(self, Vector2_0: Any, Vector2_1: Any, Vector2_2: Any, Color_3: Any) -> None: ...
    def draw_triangle_strip(self, Vector2_pointer_0: Any, int_1: int, Color_2: Any) -> None: ...
    def draw_triangle_strip_3d(self, Vector3_pointer_0: Any, int_1: int, Color_2: Any) -> None: ...
    def enable_cursor(self) -> None: ...
    def end_blend_mode(self) -> None: ...
    def end_drawing(self) -> None: ...
    def end_mode_2d(self) -> None: ...
    def end_mode_3d(self) -> None: ...
    def end_scissor_mode(self) -> None: ...
    def end_shader_mode(self) -> None: ...
    def end_texture_mode(self) -> None: ...
    def end_vr_stereo_mode(self) -> None: ...
    def export_image(self, Image_0: Any, str_1: str) -> bool: ...
    def export_image_as_code(self, Image_0: Any, str_1: str) -> bool: ...
    def export_mesh(self, Mesh_0: Any, str_1: str) -> bool: ...
    def export_wave(self, Wave_0: Any, str_1: str) -> bool: ...
    def export_wave_as_code(self, Wave_0: Any, str_1: str) -> bool: ...
    FLAG_FULLSCREEN_MODE: int
    FLAG_INTERLACED_HINT: int
    FLAG_MSAA_4X_HINT: int
    FLAG_VSYNC_HINT: int
    FLAG_WINDOW_ALWAYS_RUN: int
    FLAG_WINDOW_HIDDEN: int
    FLAG_WINDOW_HIGHDPI: int
    FLAG_WINDOW_MAXIMIZED: int
    FLAG_WINDOW_MINIMIZED: int
    FLAG_WINDOW_RESIZABLE: int
    FLAG_WINDOW_TOPMOST: int
    FLAG_WINDOW_TRANSPARENT: int
    FLAG_WINDOW_UNDECORATED: int
    FLAG_WINDOW_UNFOCUSED: int
    FONT_BITMAP: int
    FONT_DEFAULT: int
    FONT_SDF: int
    def fade(self, Color_0: Any, float_1: float) -> Any: ...
    def file_exists(self, str_0: str) -> bool: ...
    GAMEPAD_AXIS_LEFT_TRIGGER: int
    GAMEPAD_AXIS_LEFT_X: int
    GAMEPAD_AXIS_LEFT_Y: int
    GAMEPAD_AXIS_RIGHT_TRIGGER: int
    GAMEPAD_AXIS_RIGHT_X: int
    GAMEPAD_AXIS_RIGHT_Y: int
    GAMEPAD_BUTTON_LEFT_FACE_DOWN: int
    GAMEPAD_BUTTON_LEFT_FACE_LEFT: int
    GAMEPAD_BUTTON_LEFT_FACE_RIGHT: int
    GAMEPAD_BUTTON_LEFT_FACE_UP: int
    GAMEPAD_BUTTON_LEFT_THUMB: int
    GAMEPAD_BUTTON_LEFT_TRIGGER_1: int
    GAMEPAD_BUTTON_LEFT_TRIGGER_2: int
    GAMEPAD_BUTTON_MIDDLE: int
    GAMEPAD_BUTTON_MIDDLE_LEFT: int
    GAMEPAD_BUTTON_MIDDLE_RIGHT: int
    GAMEPAD_BUTTON_RIGHT_FACE_DOWN: int
    GAMEPAD_BUTTON_RIGHT_FACE_LEFT: int
    GAMEPAD_BUTTON_RIGHT_FACE_RIGHT: int
    GAMEPAD_BUTTON_RIGHT_FACE_UP: int
    GAMEPAD_BUTTON_RIGHT_THUMB: int
    GAMEPAD_BUTTON_RIGHT_TRIGGER_1: int
    GAMEPAD_BUTTON_RIGHT_TRIGGER_2: int
    GAMEPAD_BUTTON_UNKNOWN: int
    GESTURE_DOUBLETAP: int
    GESTURE_DRAG: int
    GESTURE_HOLD: int
    GESTURE_NONE: int
    GESTURE_PINCH_IN: int
    GESTURE_PINCH_OUT: int
    GESTURE_SWIPE_DOWN: int
    GESTURE_SWIPE_LEFT: int
    GESTURE_SWIPE_RIGHT: int
    GESTURE_SWIPE_UP: int
    GESTURE_TAP: int
    def gen_image_cellular(self, int_0: int, int_1: int, int_2: int) -> Any: ...
    def gen_image_checked(self, int_0: int, int_1: int, int_2: int, int_3: int, Color_4: Any, Color_5: Any) -> Any: ...
    def gen_image_color(self, int_0: int, int_1: int, Color_2: Any) -> Any: ...
    def gen_image_font_atlas(self, CharInfo_pointer_0: Any, Rectangle_pointer_pointer_1: Any, int_2: int, int_3: int, int_4: int, int_5: int) -> Any: ...
    def gen_image_gradient_h(self, int_0: int, int_1: int, Color_2: Any, Color_3: Any) -> Any: ...
    def gen_image_gradient_radial(self, int_0: int, int_1: int, float_2: float, Color_3: Any, Color_4: Any) -> Any: ...
    def gen_image_gradient_v(self, int_0: int, int_1: int, Color_2: Any, Color_3: Any) -> Any: ...
    def gen_image_perlin_noise(self, int_0: int, int_1: int, int_2: int, int_3: int, float_4: float) -> Any: ...
    def gen_image_white_noise(self, int_0: int, int_1: int, float_2: float) -> Any: ...
    def gen_mesh_cube(self, float_0: float, float_1: float, float_2: float) -> Any: ...
    def gen_mesh_cubicmap(self, Image_0: Any, Vector3_1: Any) -> Any: ...
    def gen_mesh_cylinder(self, float_0: float, float_1: float, int_2: int) -> Any: ...
    def gen_mesh_heightmap(self, Image_0: Any, Vector3_1: Any) -> Any: ...
    def gen_mesh_hemi_sphere(self, float_0: float, int_1: int, int_2: int) -> Any: ...
    def gen_mesh_knot(self, float_0: float, float_1: float, int_2: int, int_3: int) -> Any: ...
    def gen_mesh_plane(self, float_0: float, float_1: float, int_2: int, int_3: int) -> Any: ...
    def gen_mesh_poly(self, int_0: int, float_1: float) -> Any: ...
    def gen_mesh_sphere(self, float_0: float, int_1: int, int_2: int) -> Any: ...
    def gen_mesh_torus(self, float_0: float, float_1: float, int_2: int, int_3: int) -> Any: ...
    def gen_texture_mipmaps(self, Texture_pointer_0: Any) -> None: ...
    def get_camera_matrix(self, Camera3D_0: Any) -> Any: ...
    def get_camera_matrix_2d(self, Camera2D_0: Any) -> Any: ...
    def get_char_pressed(self) -> int: ...
    def get_clipboard_text(self) -> str: ...
    def get_codepoints(self, str_0: str, int_pointer_1: Any) -> Any: ...
    def get_codepoints_count(self, str_0: str) -> int: ...
    def get_collision_ray_ground(self, Ray_0: Any, float_1: float) -> Any: ...
    def get_collision_ray_mesh(self, Ray_0: Any, Mesh_1: Any, Matrix_2: Any) -> Any: ...
    def get_collision_ray_model(self, Ray_0: Any, Model_1: Any) -> Any: ...
    def get_collision_ray_triangle(self, Ray_0: Any, Vector3_1: Any, Vector3_2: Any, Vector3_3: Any) -> Any: ...
    def get_collision_rec(self, Rectangle_0: Any, Rectangle_1: Any) -> Any: ...
    def get_color(self, unsignedint_0: int) -> Any: ...
    def get_current_monitor(self) -> int: ...
    def get_directory_files(self, str_0: str, int_pointer_1: Any) -> str: ...
    def get_directory_path(self, str_0: str) -> str: ...
    def get_dropped_files(self, int_pointer_0: Any) -> str: ...
    def get_fps(self) -> int: ...
    def get_file_extension(self, str_0: str) -> str: ...
    def get_file_mod_time(self, str_0: str) -> int: ...
    def get_file_name(self, str_0: str) -> str: ...
    def get_file_name_without_ext(self, str_0: str) -> str: ...
    def get_font_default(self) -> Any: ...
    def get_frame_time(self) -> float: ...
    def get_gamepad_axis_count(self, int_0: int) -> int: ...
    def get_gamepad_axis_movement(self, int_0: int, int_1: int) -> float: ...
    def get_gamepad_button_pressed(self) -> int: ...
    def get_gamepad_name(self, int_0: int) -> str: ...
    def get_gesture_detected(self) -> int: ...
    def get_gesture_drag_angle(self) -> float: ...
    def get_gesture_drag_vector(self) -> Any: ...
    def get_gesture_hold_duration(self) -> float: ...
    def get_gesture_pinch_angle(self) -> float: ...
    def get_gesture_pinch_vector(self) -> Any: ...
    def get_glyph_index(self, Font_0: Any, int_1: int) -> int: ...
    def get_image_alpha_border(self, Image_0: Any, float_1: float) -> Any: ...
    def get_key_pressed(self) -> int: ...
    def get_monitor_count(self) -> int: ...
    def get_monitor_height(self, int_0: int) -> int: ...
    def get_monitor_name(self, int_0: int) -> str: ...
    def get_monitor_physical_height(self, int_0: int) -> int: ...
    def get_monitor_physical_width(self, int_0: int) -> int: ...
    def get_monitor_position(self, int_0: int) -> Any: ...
    def get_monitor_refresh_rate(self, int_0: int) -> int: ...
    def get_monitor_width(self, int_0: int) -> int: ...
    def get_mouse_position(self) -> Any: ...
    def get_mouse_ray(self, Vector2_0: Any, Camera3D_1: Any) -> Any: ...
    def get_mouse_wheel_move(self) -> float: ...
    def get_mouse_x(self) -> int: ...
    def get_mouse_y(self) -> int: ...
    def get_music_time_length(self, Music_0: Any) -> float: ...
    def get_music_time_played(self, Music_0: Any) -> float: ...
    def get_next_codepoint(self, str_0: str, int_pointer_1: Any) -> int: ...
    def get_pixel_color(self, void_pointer_0: Any, int_1: int) -> Any: ...
    def get_pixel_data_size(self, int_0: int, int_1: int, int_2: int) -> int: ...
    def get_prev_directory_path(self, str_0: str) -> str: ...
    def get_random_value(self, int_0: int, int_1: int) -> int: ...
    def get_screen_data(self) -> Any: ...
    def get_screen_height(self) -> int: ...
    def get_screen_to_world_2d(self, Vector2_0: Any, Camera2D_1: Any) -> Any: ...
    def get_screen_width(self) -> int: ...
    def get_shader_location(self, Shader_0: Any, str_1: str) -> int: ...
    def get_shader_location_attrib(self, Shader_0: Any, str_1: str) -> int: ...
    def get_sounds_playing(self) -> int: ...
    def get_texture_data(self, Texture_0: Any) -> Any: ...
    def get_time(self) -> float: ...
    def get_touch_points_count(self) -> int: ...
    def get_touch_position(self, int_0: int) -> Any: ...
    def get_touch_x(self) -> int: ...
    def get_touch_y(self) -> int: ...
    def get_window_handle(self) -> Any: ...
    def get_window_position(self) -> Any: ...
    def get_window_scale_dpi(self) -> Any: ...
    def get_working_directory(self) -> str: ...
    def get_world_to_screen(self, Vector3_0: Any, Camera3D_1: Any) -> Any: ...
    def get_world_to_screen_2d(self, Vector2_0: Any, Camera2D_1: Any) -> Any: ...
    def get_world_to_screen_ex(self, Vector3_0: Any, Camera3D_1: Any, int_2: int, int_3: int) -> Any: ...
    def hide_cursor(self) -> None: ...
    def image_alpha_clear(self, Image_pointer_0: Any, Color_1: Any, float_2: float) -> None: ...
    def image_alpha_crop(self, Image_pointer_0: Any, float_1: float) -> None: ...
    def image_alpha_mask(self, Image_pointer_0: Any, Image_1: Any) -> None: ...
    def image_alpha_premultiply(self, Image_pointer_0: Any) -> None: ...
    def image_clear_background(self, Image_pointer_0: Any, Color_1: Any) -> None: ...
    def image_color_brightness(self, Image_pointer_0: Any, int_1: int) -> None: ...
    def image_color_contrast(self, Image_pointer_0: Any, float_1: float) -> None: ...
    def image_color_grayscale(self, Image_pointer_0: Any) -> None: ...
    def image_color_invert(self, Image_pointer_0: Any) -> None: ...
    def image_color_replace(self, Image_pointer_0: Any, Color_1: Any, Color_2: Any) -> None: ...
    def image_color_tint(self, Image_pointer_0: Any, Color_1: Any) -> None: ...
    def image_copy(self, Image_0: Any) -> Any: ...
    def image_crop(self, Image_pointer_0: Any, Rectangle_1: Any) -> None: ...
    def image_dither(self, Image_pointer_0: Any, int_1: int, int_2: int, int_3: int, int_4: int) -> None: ...
    def image_draw(self, Image_pointer_0: Any, Image_1: Any, Rectangle_2: Any, Rectangle_3: Any, Color_4: Any) -> None: ...
    def image_draw_circle(self, Image_pointer_0: Any, int_1: int, int_2: int, int_3: int, Color_4: Any) -> None: ...
    def image_draw_circle_v(self, Image_pointer_0: Any, Vector2_1: Any, int_2: int, Color_3: Any) -> None: ...
    def image_draw_line(self, Image_pointer_0: Any, int_1: int, int_2: int, int_3: int, int_4: int, Color_5: Any) -> None: ...
    def image_draw_line_v(self, Image_pointer_0: Any, Vector2_1: Any, Vector2_2: Any, Color_3: Any) -> None: ...
    def image_draw_pixel(self, Image_pointer_0: Any, int_1: int, int_2: int, Color_3: Any) -> None: ...
    def image_draw_pixel_v(self, Image_pointer_0: Any, Vector2_1: Any, Color_2: Any) -> None: ...
    def image_draw_rectangle(self, Image_pointer_0: Any, int_1: int, int_2: int, int_3: int, int_4: int, Color_5: Any) -> None: ...
    def image_draw_rectangle_lines(self, Image_pointer_0: Any, Rectangle_1: Any, int_2: int, Color_3: Any) -> None: ...
    def image_draw_rectangle_rec(self, Image_pointer_0: Any, Rectangle_1: Any, Color_2: Any) -> None: ...
    def image_draw_rectangle_v(self, Image_pointer_0: Any, Vector2_1: Any, Vector2_2: Any, Color_3: Any) -> None: ...
    def image_draw_text(self, Image_pointer_0: Any, str_1: str, int_2: int, int_3: int, int_4: int, Color_5: Any) -> None: ...
    def image_draw_text_ex(self, Image_pointer_0: Any, Font_1: Any, str_2: str, Vector2_3: Any, float_4: float, float_5: float, Color_6: Any) -> None: ...
    def image_flip_horizontal(self, Image_pointer_0: Any) -> None: ...
    def image_flip_vertical(self, Image_pointer_0: Any) -> None: ...
    def image_format(self, Image_pointer_0: Any, int_1: int) -> None: ...
    def image_from_image(self, Image_0: Any, Rectangle_1: Any) -> Any: ...
    def image_mipmaps(self, Image_pointer_0: Any) -> None: ...
    def image_resize(self, Image_pointer_0: Any, int_1: int, int_2: int) -> None: ...
    def image_resize_canvas(self, Image_pointer_0: Any, int_1: int, int_2: int, int_3: int, int_4: int, Color_5: Any) -> None: ...
    def image_resize_nn(self, Image_pointer_0: Any, int_1: int, int_2: int) -> None: ...
    def image_rotate_ccw(self, Image_pointer_0: Any) -> None: ...
    def image_rotate_cw(self, Image_pointer_0: Any) -> None: ...
    def image_text(self, str_0: str, int_1: int, Color_2: Any) -> Any: ...
    def image_text_ex(self, Font_0: Any, str_1: str, float_2: float, float_3: float, Color_4: Any) -> Any: ...
    def image_to_pot(self, Image_pointer_0: Any, Color_1: Any) -> None: ...
    def init_audio_device(self) -> None: ...
    def init_audio_stream(self, unsignedint_0: int, unsignedint_1: int, unsignedint_2: int) -> Any: ...
    def init_window(self, int_0: int, int_1: int, str_2: str) -> None: ...
    def is_audio_device_ready(self) -> bool: ...
    def is_audio_stream_playing(self, AudioStream_0: Any) -> bool: ...
    def is_audio_stream_processed(self, AudioStream_0: Any) -> bool: ...
    def is_cursor_hidden(self) -> bool: ...
    def is_cursor_on_screen(self) -> bool: ...
    def is_file_dropped(self) -> bool: ...
    def is_file_extension(self, str_0: str, str_1: str) -> bool: ...
    def is_gamepad_available(self, int_0: int) -> bool: ...
    def is_gamepad_button_down(self, int_0: int, int_1: int) -> bool: ...
    def is_gamepad_button_pressed(self, int_0: int, int_1: int) -> bool: ...
    def is_gamepad_button_released(self, int_0: int, int_1: int) -> bool: ...
    def is_gamepad_button_up(self, int_0: int, int_1: int) -> bool: ...
    def is_gamepad_name(self, int_0: int, str_1: str) -> bool: ...
    def is_gesture_detected(self, int_0: int) -> bool: ...
    def is_key_down(self, int_0: int) -> bool: ...
    def is_key_pressed(self, int_0: int) -> bool: ...
    def is_key_released(self, int_0: int) -> bool: ...
    def is_key_up(self, int_0: int) -> bool: ...
    def is_model_animation_valid(self, Model_0: Any, ModelAnimation_1: Any) -> bool: ...
    def is_mouse_button_down(self, int_0: int) -> bool: ...
    def is_mouse_button_pressed(self, int_0: int) -> bool: ...
    def is_mouse_button_released(self, int_0: int) -> bool: ...
    def is_mouse_button_up(self, int_0: int) -> bool: ...
    def is_music_playing(self, Music_0: Any) -> bool: ...
    def is_sound_playing(self, Sound_0: Any) -> bool: ...
    def is_window_focused(self) -> bool: ...
    def is_window_fullscreen(self) -> bool: ...
    def is_window_hidden(self) -> bool: ...
    def is_window_maximized(self) -> bool: ...
    def is_window_minimized(self) -> bool: ...
    def is_window_ready(self) -> bool: ...
    def is_window_resized(self) -> bool: ...
    def is_window_state(self, unsignedint_0: int) -> bool: ...
    KEY_A: int
    KEY_APOSTROPHE: int
    KEY_B: int
    KEY_BACK: int
    KEY_BACKSLASH: int
    KEY_BACKSPACE: int
    KEY_C: int
    KEY_CAPS_LOCK: int
    KEY_COMMA: int
    KEY_D: int
    KEY_DELETE: int
    KEY_DOWN: int
    KEY_E: int
    KEY_EIGHT: int
    KEY_END: int
    KEY_ENTER: int
    KEY_EQUAL: int
    KEY_ESCAPE: int
    KEY_F: int
    KEY_F1: int
    KEY_F10: int
    KEY_F11: int
    KEY_F12: int
    KEY_F2: int
    KEY_F3: int
    KEY_F4: int
    KEY_F5: int
    KEY_F6: int
    KEY_F7: int
    KEY_F8: int
    KEY_F9: int
    KEY_FIVE: int
    KEY_FOUR: int
    KEY_G: int
    KEY_GRAVE: int
    KEY_H: int
    KEY_HOME: int
    KEY_I: int
    KEY_INSERT: int
    KEY_J: int
    KEY_K: int
    KEY_KB_MENU: int
    KEY_KP_0: int
    KEY_KP_1: int
    KEY_KP_2: int
    KEY_KP_3: int
    KEY_KP_4: int
    KEY_KP_5: int
    KEY_KP_6: int
    KEY_KP_7: int
    KEY_KP_8: int
    KEY_KP_9: int
    KEY_KP_ADD: int
    KEY_KP_DECIMAL: int
    KEY_KP_DIVIDE: int
    KEY_KP_ENTER: int
    KEY_KP_EQUAL: int
    KEY_KP_MULTIPLY: int
    KEY_KP_SUBTRACT: int
    KEY_L: int
    KEY_LEFT: int
    KEY_LEFT_ALT: int
    KEY_LEFT_BRACKET: int
    KEY_LEFT_CONTROL: int
    KEY_LEFT_SHIFT: int
    KEY_LEFT_SUPER: int
    KEY_M: int
    KEY_MENU: int
    KEY_MINUS: int
    KEY_N: int
    KEY_NINE: int
    KEY_NULL: int
    KEY_NUM_LOCK: int
    KEY_O: int
    KEY_ONE: int
    KEY_P: int
    KEY_PAGE_DOWN: int
    KEY_PAGE_UP: int
    KEY_PAUSE: int
    KEY_PERIOD: int
    KEY_PRINT_SCREEN: int
    KEY_Q: int
    KEY_R: int
    KEY_RIGHT: int
    KEY_RIGHT_ALT: int
    KEY_RIGHT_BRACKET: int
    KEY_RIGHT_CONTROL: int
    KEY_RIGHT_SHIFT: int
    KEY_RIGHT_SUPER: int
    KEY_S: int
    KEY_SCROLL_LOCK: int
    KEY_SEMICOLON: int
    KEY_SEVEN: int
    KEY_SIX: int
    KEY_SLASH: int
    KEY_SPACE: int
    KEY_T: int
    KEY_TAB: int
    KEY_THREE: int
    KEY_TWO: int
    KEY_U: int
    KEY_UP: int
    KEY_V: int
    KEY_VOLUME_DOWN: int
    KEY_VOLUME_UP: int
    KEY_W: int
    KEY_X: int
    KEY_Y: int
    KEY_Z: int
    KEY_ZERO: int
    LOG_ALL: int
    LOG_DEBUG: int
    LOG_ERROR: int
    LOG_FATAL: int
    LOG_INFO: int
    LOG_NONE: int
    LOG_TRACE: int
    LOG_WARNING: int
    def load_file_data(self, str_0: str, unsignedint_pointer_1: Any) -> str: ...
    def load_file_text(self, str_0: str) -> str: ...
    def load_font(self, str_0: str) -> Any: ...
    def load_font_data(self, unsignedstr_0: str, int_1: int, int_2: int, int_pointer_3: Any, int_4: int, int_5: int) -> Any: ...
    def load_font_ex(self, str_0: str, int_1: int, int_pointer_2: Any, int_3: int) -> Any: ...
    def load_font_from_image(self, Image_0: Any, Color_1: Any, int_2: int) -> Any: ...
    def load_font_from_memory(self, str_0: str, unsignedstr_1: str, int_2: int, int_3: int, int_pointer_4: Any, int_5: int) -> Any: ...
    def load_image(self, str_0: str) -> Any: ...
    def load_image_anim(self, str_0: str, int_pointer_1: Any) -> Any: ...
    def load_image_colors(self, Image_0: Any) -> Any: ...
    def load_image_from_memory(self, str_0: str, unsignedstr_1: str, int_2: int) -> Any: ...
    def load_image_palette(self, Image_0: Any, int_1: int, int_pointer_2: Any) -> Any: ...
    def load_image_raw(self, str_0: str, int_1: int, int_2: int, int_3: int, int_4: int) -> Any: ...
    def load_material_default(self) -> Any: ...
    def load_materials(self, str_0: str, int_pointer_1: Any) -> Any: ...
    def load_model(self, str_0: str) -> Any: ...
    def load_model_animations(self, str_0: str, int_pointer_1: Any) -> Any: ...
    def load_model_from_mesh(self, Mesh_0: Any) -> Any: ...
    def load_music_stream(self, str_0: str) -> Any: ...
    def load_music_stream_from_memory(self, str_0: str, unsignedstr_1: str, int_2: int) -> Any: ...
    def load_render_texture(self, int_0: int, int_1: int) -> Any: ...
    def load_shader(self, str_0: str, str_1: str) -> Any: ...
    def load_shader_from_memory(self, str_0: str, str_1: str) -> Any: ...
    def load_sound(self, str_0: str) -> Any: ...
    def load_sound_from_wave(self, Wave_0: Any) -> Any: ...
    def load_storage_value(self, unsignedint_0: int) -> int: ...
    def load_texture(self, str_0: str) -> Any: ...
    def load_texture_cubemap(self, Image_0: Any, int_1: int) -> Any: ...
    def load_texture_from_image(self, Image_0: Any) -> Any: ...
    def load_vr_stereo_config(self, VrDeviceInfo_0: Any) -> Any: ...
    def load_wave(self, str_0: str) -> Any: ...
    def load_wave_from_memory(self, str_0: str, unsignedstr_1: str, int_2: int) -> Any: ...
    def load_wave_samples(self, Wave_0: Any) -> Any: ...
    MATERIAL_MAP_ALBEDO: int
    MATERIAL_MAP_BRDG: int
    MATERIAL_MAP_CUBEMAP: int
    MATERIAL_MAP_DIFFUSE: int
    MATERIAL_MAP_EMISSION: int
    MATERIAL_MAP_HEIGHT: int
    MATERIAL_MAP_IRRADIANCE: int
    MATERIAL_MAP_METALNESS: int
    MATERIAL_MAP_NORMAL: int
    MATERIAL_MAP_OCCLUSION: int
    MATERIAL_MAP_PREFILTER: int
    MATERIAL_MAP_ROUGHNESS: int
    MATERIAL_MAP_SPECULAR: int
    MOUSE_CURSOR_ARROW: int
    MOUSE_CURSOR_CROSSHAIR: int
    MOUSE_CURSOR_DEFAULT: int
    MOUSE_CURSOR_IBEAM: int
    MOUSE_CURSOR_NOT_ALLOWED: int
    MOUSE_CURSOR_POINTING_HAND: int
    MOUSE_CURSOR_RESIZE_ALL: int
    MOUSE_CURSOR_RESIZE_EW: int
    MOUSE_CURSOR_RESIZE_NESW: int
    MOUSE_CURSOR_RESIZE_NS: int
    MOUSE_CURSOR_RESIZE_NWSE: int
    MOUSE_LEFT_BUTTON: int
    MOUSE_MIDDLE_BUTTON: int
    MOUSE_RIGHT_BUTTON: int
    def maximize_window(self) -> None: ...
    def measure_text(self, str_0: str, int_1: int) -> int: ...
    def measure_text_ex(self, Font_0: Any, str_1: str, float_2: float, float_3: float) -> Any: ...
    def mem_alloc(self, int_0: int) -> Any: ...
    def mem_free(self, void_pointer_0: Any) -> None: ...
    def mem_realloc(self, void_pointer_0: Any, int_1: int) -> Any: ...
    def mesh_binormals(self, Mesh_pointer_0: Any) -> None: ...
    def mesh_bounding_box(self, Mesh_0: Any) -> Any: ...
    def mesh_tangents(self, Mesh_pointer_0: Any) -> None: ...
    def minimize_window(self) -> None: ...
    NPATCH_NINE_PATCH: int
    NPATCH_THREE_PATCH_HORIZONTAL: int
    NPATCH_THREE_PATCH_VERTICAL: int
    def open_url(self, str_0: str) -> None: ...
    PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA: int
    PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA: int
    PIXELFORMAT_COMPRESSED_DXT1_RGB: int
    PIXELFORMAT_COMPRESSED_DXT1_RGBA: int
    PIXELFORMAT_COMPRESSED_DXT3_RGBA: int
    PIXELFORMAT_COMPRESSED_DXT5_RGBA: int
    PIXELFORMAT_COMPRESSED_ETC1_RGB: int
    PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA: int
    PIXELFORMAT_COMPRESSED_ETC2_RGB: int
    PIXELFORMAT_COMPRESSED_PVRT_RGB: int
    PIXELFORMAT_COMPRESSED_PVRT_RGBA: int
    PIXELFORMAT_UNCOMPRESSED_GRAYSCALE: int
    PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA: int
    PIXELFORMAT_UNCOMPRESSED_R32: int
    PIXELFORMAT_UNCOMPRESSED_R32G32B32: int
    PIXELFORMAT_UNCOMPRESSED_R32G32B32A32: int
    PIXELFORMAT_UNCOMPRESSED_R4G4B4A4: int
    PIXELFORMAT_UNCOMPRESSED_R5G5B5A1: int
    PIXELFORMAT_UNCOMPRESSED_R5G6B5: int
    PIXELFORMAT_UNCOMPRESSED_R8G8B8: int
    PIXELFORMAT_UNCOMPRESSED_R8G8B8A8: int
    def pause_audio_stream(self, AudioStream_0: Any) -> None: ...
    def pause_music_stream(self, Music_0: Any) -> None: ...
    def pause_sound(self, Sound_0: Any) -> None: ...
    def play_audio_stream(self, AudioStream_0: Any) -> None: ...
    def play_music_stream(self, Music_0: Any) -> None: ...
    def play_sound(self, Sound_0: Any) -> None: ...
    def play_sound_multi(self, Sound_0: Any) -> None: ...
    def restore_window(self) -> None: ...
    def resume_audio_stream(self, AudioStream_0: Any) -> None: ...
    def resume_music_stream(self, Music_0: Any) -> None: ...
    def resume_sound(self, Sound_0: Any) -> None: ...
    SHADER_LOC_COLOR_AMBIENT: int
    SHADER_LOC_COLOR_DIFFUSE: int
    SHADER_LOC_COLOR_SPECULAR: int
    SHADER_LOC_MAP_ALBEDO: int
    SHADER_LOC_MAP_BRDF: int
    SHADER_LOC_MAP_CUBEMAP: int
    SHADER_LOC_MAP_DIFFUSE: int
    SHADER_LOC_MAP_EMISSION: int
    SHADER_LOC_MAP_HEIGHT: int
    SHADER_LOC_MAP_IRRADIANCE: int
    SHADER_LOC_MAP_METALNESS: int
    SHADER_LOC_MAP_NORMAL: int
    SHADER_LOC_MAP_OCCLUSION: int
    SHADER_LOC_MAP_PREFILTER: int
    SHADER_LOC_MAP_ROUGHNESS: int
    SHADER_LOC_MAP_SPECULAR: int
    SHADER_LOC_MATRIX_MODEL: int
    SHADER_LOC_MATRIX_MVP: int
    SHADER_LOC_MATRIX_NORMAL: int
    SHADER_LOC_MATRIX_PROJECTION: int
    SHADER_LOC_MATRIX_VIEW: int
    SHADER_LOC_VECTOR_VIEW: int
    SHADER_LOC_VERTEX_COLOR: int
    SHADER_LOC_VERTEX_NORMAL: int
    SHADER_LOC_VERTEX_POSITION: int
    SHADER_LOC_VERTEX_TANGENT: int
    SHADER_LOC_VERTEX_TEXCOORD01: int
    SHADER_LOC_VERTEX_TEXCOORD02: int
    SHADER_UNIFORM_FLOAT: int
    SHADER_UNIFORM_INT: int
    SHADER_UNIFORM_IVEC2: int
    SHADER_UNIFORM_IVEC3: int
    SHADER_UNIFORM_IVEC4: int
    SHADER_UNIFORM_SAMPLER2D: int
    SHADER_UNIFORM_VEC2: int
    SHADER_UNIFORM_VEC3: int
    SHADER_UNIFORM_VEC4: int
    def save_file_data(self, str_0: str, void_pointer_1: Any, unsignedint_2: int) -> bool: ...
    def save_file_text(self, str_0: str, str_1: str) -> bool: ...
    def save_storage_value(self, unsignedint_0: int, int_1: int) -> bool: ...
    def set_audio_stream_buffer_size_default(self, int_0: int) -> None: ...
    def set_audio_stream_pitch(self, AudioStream_0: Any, float_1: float) -> None: ...
    def set_audio_stream_volume(self, AudioStream_0: Any, float_1: float) -> None: ...
    def set_camera_alt_control(self, int_0: int) -> None: ...
    def set_camera_mode(self, Camera3D_0: Any, int_1: int) -> None: ...
    def set_camera_move_controls(self, int_0: int, int_1: int, int_2: int, int_3: int, int_4: int, int_5: int) -> None: ...
    def set_camera_pan_control(self, int_0: int) -> None: ...
    def set_camera_smooth_zoom_control(self, int_0: int) -> None: ...
    def set_clipboard_text(self, str_0: str) -> None: ...
    def set_config_flags(self, unsignedint_0: int) -> None: ...
    def set_exit_key(self, int_0: int) -> None: ...
    def set_gamepad_mappings(self, str_0: str) -> int: ...
    def set_gestures_enabled(self, unsignedint_0: int) -> None: ...
    def set_master_volume(self, float_0: float) -> None: ...
    def set_material_texture(self, Material_pointer_0: Any, int_1: int, Texture_2: Any) -> None: ...
    def set_model_mesh_material(self, Model_pointer_0: Any, int_1: int, int_2: int) -> None: ...
    def set_mouse_cursor(self, int_0: int) -> None: ...
    def set_mouse_offset(self, int_0: int, int_1: int) -> None: ...
    def set_mouse_position(self, int_0: int, int_1: int) -> None: ...
    def set_mouse_scale(self, float_0: float, float_1: float) -> None: ...
    def set_music_pitch(self, Music_0: Any, float_1: float) -> None: ...
    def set_music_volume(self, Music_0: Any, float_1: float) -> None: ...
    def set_pixel_color(self, void_pointer_0: Any, Color_1: Any, int_2: int) -> None: ...
    def set_shader_value(self, Shader_0: Any, int_1: int, void_pointer_2: Any, int_3: int) -> None: ...
    def set_shader_value_matrix(self, Shader_0: Any, int_1: int, Matrix_2: Any) -> None: ...
    def set_shader_value_texture(self, Shader_0: Any, int_1: int, Texture_2: Any) -> None: ...
    def set_shader_value_v(self, Shader_0: Any, int_1: int, void_pointer_2: Any, int_3: int, int_4: int) -> None: ...
    def set_shapes_texture(self, Texture_0: Any, Rectangle_1: Any) -> None: ...
    def set_sound_pitch(self, Sound_0: Any, float_1: float) -> None: ...
    def set_sound_volume(self, Sound_0: Any, float_1: float) -> None: ...
    def set_target_fps(self, int_0: int) -> None: ...
    def set_texture_filter(self, Texture_0: Any, int_1: int) -> None: ...
    def set_texture_wrap(self, Texture_0: Any, int_1: int) -> None: ...
    def set_trace_log_level(self, int_0: int) -> None: ...
    def set_window_icon(self, Image_0: Any) -> None: ...
    def set_window_min_size(self, int_0: int, int_1: int) -> None: ...
    def set_window_monitor(self, int_0: int) -> None: ...
    def set_window_position(self, int_0: int, int_1: int) -> None: ...
    def set_window_size(self, int_0: int, int_1: int) -> None: ...
    def set_window_state(self, unsignedint_0: int) -> None: ...
    def set_window_title(self, str_0: str) -> None: ...
    def show_cursor(self) -> None: ...
    def stop_audio_stream(self, AudioStream_0: Any) -> None: ...
    def stop_music_stream(self, Music_0: Any) -> None: ...
    def stop_sound(self, Sound_0: Any) -> None: ...
    def stop_sound_multi(self) -> None: ...
    TEXTURE_FILTER_ANISOTROPIC_16X: int
    TEXTURE_FILTER_ANISOTROPIC_4X: int
    TEXTURE_FILTER_ANISOTROPIC_8X: int
    TEXTURE_FILTER_BILINEAR: int
    TEXTURE_FILTER_POINT: int
    TEXTURE_FILTER_TRILINEAR: int
    TEXTURE_WRAP_CLAMP: int
    TEXTURE_WRAP_MIRROR_CLAMP: int
    TEXTURE_WRAP_MIRROR_REPEAT: int
    TEXTURE_WRAP_REPEAT: int
    def take_screenshot(self, str_0: str) -> None: ...
    def text_append(self, str_0: str, str_1: str, int_pointer_2: Any) -> None: ...
    def text_copy(self, str_0: str, str_1: str) -> int: ...
    def text_find_index(self, str_0: str, str_1: str) -> int: ...
    TextFormat: _cffi_backend._CDataBase
    def text_insert(self, str_0: str, str_1: str, int_2: int) -> str: ...
    def text_is_equal(self, str_0: str, str_1: str) -> bool: ...
    def text_join(self, str_pointer_0: str, int_1: int, str_2: str) -> str: ...
    def text_length(self, str_0: str) -> int: ...
    def text_replace(self, str_0: str, str_1: str, str_2: str) -> str: ...
    def text_split(self, str_0: str, char_1: char, int_pointer_2: Any) -> str: ...
    def text_subtext(self, str_0: str, int_1: int, int_2: int) -> str: ...
    def text_to_integer(self, str_0: str) -> int: ...
    def text_to_lower(self, str_0: str) -> str: ...
    def text_to_pascal(self, str_0: str) -> str: ...
    def text_to_upper(self, str_0: str) -> str: ...
    def text_to_utf8(self, int_pointer_0: Any, int_1: int) -> str: ...
    def toggle_fullscreen(self) -> None: ...
    TraceLog: _cffi_backend._CDataBase
    def unload_file_data(self, unsignedstr_0: str) -> None: ...
    def unload_file_text(self, unsignedstr_0: str) -> None: ...
    def unload_font(self, Font_0: Any) -> None: ...
    def unload_font_data(self, CharInfo_pointer_0: Any, int_1: int) -> None: ...
    def unload_image(self, Image_0: Any) -> None: ...
    def unload_image_colors(self, Color_pointer_0: Any) -> None: ...
    def unload_image_palette(self, Color_pointer_0: Any) -> None: ...
    def unload_material(self, Material_0: Any) -> None: ...
    def unload_mesh(self, Mesh_0: Any) -> None: ...
    def unload_model(self, Model_0: Any) -> None: ...
    def unload_model_animation(self, ModelAnimation_0: Any) -> None: ...
    def unload_model_animations(self, ModelAnimation_pointer_0: Any, unsignedint_1: int) -> None: ...
    def unload_model_keep_meshes(self, Model_0: Any) -> None: ...
    def unload_music_stream(self, Music_0: Any) -> None: ...
    def unload_render_texture(self, RenderTexture_0: Any) -> None: ...
    def unload_shader(self, Shader_0: Any) -> None: ...
    def unload_sound(self, Sound_0: Any) -> None: ...
    def unload_texture(self, Texture_0: Any) -> None: ...
    def unload_vr_stereo_config(self, VrStereoConfig_0: Any) -> None: ...
    def unload_wave(self, Wave_0: Any) -> None: ...
    def unload_wave_samples(self, float_pointer_0: Any) -> None: ...
    def update_audio_stream(self, AudioStream_0: Any, void_pointer_1: Any, int_2: int) -> None: ...
    def update_camera(self, Camera3D_pointer_0: Any) -> None: ...
    def update_mesh_buffer(self, Mesh_0: Any, int_1: int, void_pointer_2: Any, int_3: int, int_4: int) -> None: ...
    def update_model_animation(self, Model_0: Any, ModelAnimation_1: Any, int_2: int) -> None: ...
    def update_music_stream(self, Music_0: Any) -> None: ...
    def update_sound(self, Sound_0: Any, void_pointer_1: Any, int_2: int) -> None: ...
    def update_texture(self, Texture_0: Any, void_pointer_1: Any) -> None: ...
    def update_texture_rec(self, Texture_0: Any, Rectangle_1: Any, void_pointer_2: Any) -> None: ...
    def upload_mesh(self, Mesh_pointer_0: Any, _Bool_1: bool) -> None: ...
    def wave_copy(self, Wave_0: Any) -> Any: ...
    def wave_crop(self, Wave_pointer_0: Any, int_1: int, int_2: int) -> None: ...
    def wave_format(self, Wave_pointer_0: Any, int_1: int, int_2: int, int_3: int) -> None: ...
    def window_should_close(self) -> bool: ...
    AudioStream: Any
    BlendMode: Any
    BoneInfo: Any
    BoundingBox: Any
    Camera: Any
    Camera2D: Any
    Camera3D: Any
    CameraMode: Any
    CameraProjection: Any
    CharInfo: Any
    Color: Any
    ConfigFlags: Any
    CubemapLayout: Any
    Font: Any
    FontType: Any
    GamepadAxis: Any
    GamepadButton: Any
    Gestures: Any
    Image: Any
    KeyboardKey: Any
    Material: Any
    MaterialMap: Any
    MaterialMapIndex: Any
    Matrix: Any
    Mesh: Any
    Model: Any
    ModelAnimation: Any
    MouseButton: Any
    MouseCursor: Any
    Music: Any
    NPatchInfo: Any
    NPatchLayout: Any
    PixelFormat: Any
    Quaternion: Any
    Ray: Any
    RayHitInfo: Any
    Rectangle: Any
    RenderTexture: Any
    RenderTexture2D: Any
    Shader: Any
    ShaderLocationIndex: Any
    ShaderUniformDataType: Any
    Sound: Any
    Texture: Any
    Texture2D: Any
    TextureCubemap: Any
    TextureFilter: Any
    TextureWrap: Any
    TraceLogLevel: Any
    Transform: Any
    Vector2: Any
    Vector3: Any
    Vector4: Any
    VrDeviceInfo: Any
    VrStereoConfig: Any
    Wave: Any
    rAudioBuffer: Any
